# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    user_resource:
        class: AppBundle\JsonApiResource\UserResource
        tags:
            - { name: jsonapi.resource }
    foo_resource:
        class: AppBundle\JsonApiResource\FooResource
        tags:
            - { name: jsonapi.resource }
    author_resource:
        class: AppBundle\JsonApiResource\AuthorResource
        tags:
            - { name: jsonapi.resource }
    book_resource:
        class: AppBundle\JsonApiResource\BookResource
        tags:
            - { name: jsonapi.resource }
